import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { motion, useReducedMotion } from 'framer-motion';
import { ArrowDown, ArrowUpRight, Compass, Menu, Plane, Send, X } from 'lucide-react';
import './styles.css';

const stops = [['home','00','Home'],['about','01','About'],['education','02','Education'],['experience','03','Experience'],['skills','04','Skills'],['sabre','05','Sabre'],['languages','06','Languages'],['cv','07','CV'],['contact','08','Contact']];
const education = [['SEE','Valley Public High School','GPA 3.70'],['+2','Xavier International College','GPA 3.38'],['NATHM','Bachelor in Travel and Tourism Management','2nd Semester']];
const skillGroups = [['Travel & Tourism',['Trekking Guide','Flight Booking','Basic Ticketing','PNR Creation']],['Travel Technology',['Sabre Knowledge','Passenger Reservation','GDS','Fare Structures']],['Communication & Marketing',['Communication Skills','Marketing Skills','Content Creation','Social Media','Web Content']]];

function JourneyMap({active,go}) { return <aside className="journey-map" aria-label="Journey navigation"><p>Journey status <b>in transit</b></p><svg viewBox="0 0 120 570" aria-hidden="true"><path d="M65 12C14 75 111 111 57 167S12 250 62 298 115 374 55 425 23 508 70 558" /></svg><div className="map-stops">{stops.map(([id,n,label],i)=><button key={id} onClick={()=>go(id)} className={active===id?'active':''} aria-label={`Go to ${label}`}><i>{n}</i><span>{label}</span><em>{active===id?'●':i<stops.findIndex(s=>s[0]===active)?'•':'○'}</em></button>)}</div></aside> }
function MountainScene({night=false}) { return <div className={`mountains ${night?'night':''}`} aria-hidden="true"><div className="stars"/><div className="cloud cloud-a"/><div className="cloud cloud-b"/><svg viewBox="0 0 1440 500" preserveAspectRatio="none"><path className="far" d="M0 350 130 220 255 310 425 120 560 300 730 165 900 315 1070 130 1240 280 1440 180V500H0Z"/><path className="mid" d="M0 380 155 245 310 360 515 205 690 365 900 190 1100 340 1280 215 1440 330V500H0Z"/><path className="near" d="M0 430 210 300 380 415 590 275 790 420 1030 285 1210 405 1440 300V500H0Z"/></svg></div> }
function Intro({n,label,children}) { return <div className="intro"><p><span>{n}</span> — {label}</p><h2>{children}</h2></div> }

function App(){
 const [active,setActive]=useState('home'),[menu,setMenu]=useState(false),[form,setForm]=useState('idle'),[flight,setFlight]=useState(false); const reduce=useReducedMotion();
 const go=id=>{document.getElementById(id)?.scrollIntoView({behavior:reduce?'auto':'smooth',block:'start'});setMenu(false)};
 useEffect(()=>{const o=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&setActive(e.target.id)),{rootMargin:'-36% 0px -52% 0px'});stops.forEach(([id])=>{const e=document.getElementById(id);if(e)o.observe(e)});return()=>o.disconnect()},[]);
 async function submit(e){e.preventDefault();setForm('sending');try{const r=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});if(!r.ok)throw Error();setForm('sent');e.currentTarget.reset()}catch{setForm('error')}}
 return <div className="app"><header><a className="wordmark" href="#home">ADITYA <i>ADHIKARI</i></a><nav className={menu?'open':''}>{stops.map(([id,n,label])=><button key={id} onClick={()=>go(id)} className={active===id?'selected':''}>[{n}] {label}</button>)}</nav><button className="menu" onClick={()=>setMenu(!menu)} aria-label="Toggle menu">{menu?<X/>:<Menu/>}</button></header><JourneyMap active={active} go={go}/><button className="compass" onClick={()=>document.querySelector('.journey-map')?.classList.toggle('shown')} aria-label="Open journey map"><Compass/></button><main>
 <section className="hero section" id="home"><MountainScene/><div className="hero-content"><motion.p initial={{opacity:0}} animate={{opacity:1}} className="eyebrow">27°42'N / 85°19'E <span>visual reference</span></motion.p><motion.h1 initial={{opacity:0,y:28}} animate={{opacity:1,y:0}} transition={{duration:.8}}>ADITYA<br/><i>ADHIKARI</i></motion.h1><motion.div initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.35}}><p className="hero-role">STUDENT <b/> TRAVEL &amp; TOURISM</p><p className="hero-copy">Exploring places.<br/>Connecting people.<br/>Building a journey.</p><button className="signal-button" onClick={()=>go('about')}>Explore my journey <ArrowDown/></button></motion.div></div><div className="hero-route"><span>START</span><svg viewBox="0 0 560 150"><path d="M2 130C105 15 210 155 318 68S470 20 556 50"/><circle cx="2" cy="130" r="5"/><circle cx="556" cy="50" r="5"/></svg><span>BASE CAMP</span></div></section>
 <section className="section about" id="about"><div className="container"><Intro n="01" label="ABOUT THE TRAVELER">A journey made<br/><i>with intention.</i></Intro><div className="journal"><div className="profile"><img src="/images/Aditya.png" alt="Aditya Adhikari"/><span>Expedition briefing / 001</span></div><div><p className="lead">Highly motivated and detail-oriented student in Bachelor of Travel and Tourism Management (2nd Semester) at NATHM, passionate about the travel industry.</p><p>Possesses strong communication, interpersonal, and customer service skills, honed through education and recent training. Demonstrated ability in effective time management and decision-making. Eager to leverage skills in a dynamic travel environment.</p><div className="coordinate">TRAVELER'S NOTE <b>KEEP MOVING FORWARD</b></div></div></div></div></section>
 <section className="section education" id="education"><div className="container"><Intro n="02" label="EDUCATION">Elevation<br/><i>milestones.</i></Intro><div className="elevation">{education.map(([mark,school,result],i)=><article key={mark}><span>{String(i+1).padStart(2,'0')}</span><i className="pin"/><div><b>{mark}</b><h3>{school}</h3><p>{result}</p></div>{i<2&&<small>ASCENT</small>}</article>)}<div className="future">SUMMIT → FUTURE</div></div></div></section>
 <section className="section experience" id="experience"><div className="container"><Intro n="03" label="EXPERIENCE">Runway to<br/><i>new knowledge.</i></Intro><article className="boarding"><div className="ticket-top"><span>SABRE NEPAL</span><span>TRAINING PASS / 2026</span></div><div className="flight-line"><b>KTM</b><div><Plane/><i/></div><b>GDS</b></div><div className="ticket-info"><div><small>PROGRAM</small><strong>Basic Ticketing Training</strong></div><div><small>DATES</small><strong>February 13 – February 20, 2026</strong></div></div><p>Completed comprehensive, one-week basic ticketing training on Sabre Global Distribution System (GDS). Gained practical knowledge in passenger reservation systems and fare structures. Developed familiarity with industry-standard ticketing protocols and GDS command language.</p></article></div></section>
 <section className="section skills" id="skills"><MountainScene/><div className="container"><Intro n="04" label="SKILLS">Destination<br/><i>skills.</i></Intro><div className="camp-grid">{skillGroups.map(([name,items],i)=><article key={name}><span>0{i+1} / BASE CAMP</span><h3>{name}</h3><ul>{items.map(item=><li key={item}><i/> {item}</li>)}</ul></article>)}</div></div></section>
 <section className="section sabre" id="sabre"><div className="container"><Intro n="05" label="SABRE / TICKETING">Terminal<br/><i>ready.</i></Intro><div className="terminal"><div className="terminal-head"><span>● SYSTEM ONLINE</span><span>VISUAL SIMULATION</span></div><pre>{'> SABRE GDS\n> AVAIL KTMDEL\n> PASSENGER: ADITYA/ADHIKARI\n> PNR CREATE\n> FLIGHT BOOKING\n> FARE CHECK\n> STATUS: READY_'}</pre><div className="pnr">PNR <b>CREATED</b></div></div><div className="flight-desk"><div><p>FLIGHT DESK <span>DEMO / SIMULATION</span></p><div className="fields"><label>FROM<input defaultValue="KTM"/></label><label>TO<input defaultValue="DEL"/></label><label>DATE<input defaultValue="20 SEP"/></label><label>PASSENGERS<input defaultValue="01"/></label></div></div><button onClick={()=>setFlight(true)}>Search flights <ArrowUpRight/></button>{flight&&<div className="flight-result"><span>DEMO FLIGHT</span><b>KTM → DEL</b><small>01h 45m · DEMO PNR AD7X9K</small></div>}</div></div></section>
 <section className="section languages" id="languages"><div className="container"><Intro n="06" label="LANGUAGES">Routes of<br/><i>connection.</i></Intro><div className="language-list">{['English','नेपाली','हिन्दी'].map((l,i)=><div key={l}><span>0{i+1}</span><h3>{l}</h3><p>Communication route active</p><ArrowUpRight/></div>)}</div><div className="dna"><span>MY TRAVEL DNA</span>{['Communication','Customer Service','Time Management','Decision Making','Marketing','Travel Technology'].map(x=><b key={x}>{x}</b>)}</div></div></section>
 <section className="section cv" id="cv"><div className="container"><Intro n="07" label="CURRICULUM VITAE">The complete<br/><i>journey.</i></Intro><div className="cv-viewer"><div className="cv-viewer-head"><span>CV / ADITYA ADHIKARI</span><span>VIEWING DOCUMENT</span></div><iframe src="/images/Aditya_Adhikari_Resume.pdf#toolbar=0&navpanes=0" title="Aditya Adhikari curriculum vitae"/></div></div></section>
 <section className="section contact" id="contact"><MountainScene night/><div className="container"><Intro n="08" label="FINAL DESTINATION">Ready for the<br/><i>next journey?</i></Intro><div className="contact-layout"><div className="contact-details"><p>Send a travel signal to begin a conversation.</p><a href="tel:+9779748261524">+977 9748261524</a><a href="mailto:adityadhikiral000@gmail.com">adityadhikiral000@gmail.com</a><span>Pasikot, Budanilkantha</span></div><form onSubmit={submit}><label>Name<input name="name" required placeholder="Your name"/></label><label>Email<input name="email" type="email" required placeholder="you@example.com"/></label><label>Subject<input name="subject" required placeholder="A reason to connect"/></label><label>Message<textarea name="message" required minLength="10" placeholder="Your message"/></label><button className="signal-button" disabled={form==='sending'}>{form==='sent'?'Signal sent ✓':form==='sending'?'Transmitting...':<>Send message <Send/></>}</button>{form==='error'&&<p className="error">Signal interrupted. Please try again.</p>}</form></div></div></section>
 </main><footer>© 2026 ADITYA ADHIKARI <span>TRAVEL &amp; TOURISM / JOURNEY CONTINUES</span></footer></div>
}
createRoot(document.getElementById('root')).render(<App/>);
